Bump minor version, add VERSION file, update to latest mkrelease

diff --git a/mkrelease b/mkrelease
--- a/mkrelease
+++ b/mkrelease
@@ -1,31 +1,24 @@
 #!/bin/bash
 
-VERSION="1.0.2"
-RELEASE=4
+[ -f VERSION ] || {
+    echo "VERSION file missing. Exiting."
+    exit 1
+}
+. ./VERSION
 
 usage() {
-    printf "\nUsage: mkrelease [-c] [-d] [-p] [-u]"
+    printf "\nUsage: mkrelease [-d] [-u]"
     printf "\nWhere:"
-    printf "\n\t-c indicates clean first"
     printf "\n\t-d indicates create draft release"
-    printf "\n\t-p indicates skip package creation step"
     printf "\n\t-u displays this usage message and exits\n"
     exit 1
 }
 
-CLEAN=
 DRAFT=
-PACKAGE=1
-while getopts "cdpu" flag; do
+while getopts "du" flag; do
     case $flag in
-        c)
-            CLEAN=1
-            ;;
         d)
             DRAFT="--draft"
-            ;;
-        p)
-            PACKAGE=
             ;;
         u)
             usage
@@ -34,7 +27,10 @@ while getopts "cdpu" flag; do
 done
 shift $(( OPTIND - 1 ))
 
-ANNO="Obsidian Custom Discogs Vault, Version ${VERSION} Release ${RELEASE}"
+ANNO="Obsidian Custom Discogs Vault, version ${VERSION}r${RELEASE}"
+gittag v${VERSION}r${RELEASE} ${ANNO}
+
+echo "Creating release for version ${VERSION} release ${RELEASE}"
 
 gh release create v${VERSION}r${RELEASE} ${DRAFT} \
                   --title "${ANNO}" \
